version: '3.9'
services:
  mongo:
    image: mongo
    volumes:
      - mongo_data:/data
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  # library:
  #   build: .
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - PORT=3000
  #     - APP_COUNTER_BOOKS_HOST=http://counter-books:3002
  #     - DATABASE_PATH=mongodb://root:example@mongo:27017/
  #   depends_on:
  #     - counter-books
  #     - mongo

volumes:
  mongo_data: {}
